services:
  api-report:
    container_name: api-report
    build:
      context: .docker/node
      dockerfile: Dockerfile
    entrypoint: .docker/node/entrypoint.sh
    ports:
      - "4000:4000"
      - "7000:7000"
    volumes:
      - .:/home/node/app

  db-report:
    container_name: db-test-report
    build:
      context: .docker/postgres
      dockerfile: Dockerfile
    command: postgres -c log_statement=all
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: testreport
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
